services:
  backend:
    container_name: backend
    build: .
    ports:
      - "8000:8000"
    environment:
      - APP_CONFIG__DB__URL=postgresql+asyncpg://postgres:postgres@db:5432/effectivedb
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=effectivedb